apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: thing-controller-role
  namespace: thing
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thing-controller-rolebinding
  namespace: thing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: thing-controller-role
subjects:
- kind: ServiceAccount
  name: thing-controller
  namespace: thing
